services:
    mongo_db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - volume_1:/data/db1

    my_app2:
        build: .
        ports:
            - "3000:3000"
        # volumes:
        #     - .:/usr/src/app

volumes:
    volume_1:
